### ISSUE TITLE
讨论1

### ISSUE THREAD

**Issue by KiwataHoko** [Lizard-Lab/draft#1]
1. 思想：揭示“正常”的标准所蕴藏的暴力
2. 背景：“网瘾学校”（青少年矫正机构）
3. 游戏类型：
（1）角色扮演
（2）模拟经营

**Comment by pro0k** [comment]
RPG是我原本的想法。设定是一个女高中生被送进矫正机构，通过和多个人周旋，处理事件，收集物品来走向不同的结局。

昨天群里想了个RPG的游戏机制。把主角的‘特性’，分为2个维度：服从～反抗 和 疯狂～理性。两个维度就是四个结局，或者加一个普通结局。根据游戏的氛围。玩家的疯狂是逐日增加额的。理性要做特别的选择遇到特别的事件进行维持。设计两到三个长事件。十到二十个短事件。四到八个契机事件。

**Comment by cijiugechu** [comment]
`特性`属于玩家可见吗，如果不可见的话，是否需要流程中的隐性暗示？

**Comment by pro0k** [comment]
我认为允许特色玩家代入正是游戏这一载体的包容

**Comment by cijiugechu** [comment]
模拟经营的话可能需要更多数值的设计？当前我们是否有一定的关于这种机构的运行模式的报道？

**Comment by cijiugechu** [comment]
> 模拟经营的话可能需要更多数值的设计？当前我们是否有一定的关于这种机构的运行模式的报道？

比如资金来源，靠山，工作人员构成

**Comment by bleed-knife** [comment]
窝姥提个两点小建议，一个是确立大框架，确定我们要写一个什么样的游戏，是模拟经营矫正学校，还是角色扮演一个进入这种学校的人。第二个就是我们最好积累一点生活经验，比如去查阅相关人士的报道，让玩家游玩时能够更有感觉。毕竟这是一个严肃的主题，如果翻车，对于受害者产生二次伤害啥的，这都不是我们希望发生的。
一点小建议，仅供参考……

**Comment by pro0k** [comment]
> 模拟经营的话可能需要更多数值的设计？当前我们是否有一定的关于这种机构的运行模式的报道？

网上有非常多亲历者的描述

**Comment by cijiugechu** [comment]
> > 模拟经营的话可能需要更多数值的设计？当前我们是否有一定的关于这种机构的运行模式的报道？
> 
> 网上有非常多亲历者的描述

方便放几个相关链接到文档里吗，或者贴在这里我去加

**Comment by pro0k** [comment]
> > > 模拟经营的话可能需要更多数值的设计？当前我们是否有一定的关于这种机构的运行模式的报道？
> > 
> > 
> > 网上有非常多亲历者的描述
> 
> 方便放几个相关链接到文档里吗，或者贴在这里我去加

好的，我去搜索补充

**Comment by pro0k** [comment]
> > > 模拟经营的话可能需要更多数值的设计？当前我们是否有一定的关于这种机构的运行模式的报道？
> > 
> > 
> > 网上有非常多亲历者的描述
> 
> 方便放几个相关链接到文档里吗，或者贴在这里我去加

已经贴上去了一些

**Comment by pro0k** [comment]
我在想是不是可以来点福柯

**Comment by cijiugechu** [comment]
> 我在想是不是可以来点福柯

如何融入比较好呢，如果是模拟经营类，似乎不太好加？

**Comment by pro0k** [comment]
> > 我在想是不是可以来点福柯
> 
> 如何融入比较好呢，如果是模拟经营类，似乎不太好加？

我的意思是这个涉及精神病学，有福柯内味了
