### ISSUE TITLE
游戏名：《保卫东京铁塔》

### ISSUE THREAD

**Issue by KiwataHoko** [Lizard-Lab/draft#2]
类型：类角色扮演，塔防
内容：美日安保条约的签订，又一次搅动了二战后风云激荡的新日本。在反安保运动中，激进的群众占领了日本的喉舌，东京电视塔。玩家将与年纪轻轻的少女指挥官并肩，与企图夺回塔的军警展开攻防战。

**Comment by cijiugechu** [comment]
玩家操控的是进攻方？反过来的话似乎缺少足够多样的防守手段

**Comment by pro0k** [comment]
玩家是守方。我初步设定为东京塔是运动最后的据点。

**Comment by cijiugechu** [comment]
防守方式也许可以通过获取军警掉落的物品来增加多样性

**Comment by pro0k** [comment]
这个可以有
